#ifndef MARLAIS_LIMITS_H
#define MARLAIS_LIMITS_H

#define MAX_STRING_SIZE 10240
#define MAX_SYMBOL_SIZE 1024
#define MAX_NUMBER_SIZE 255
#define DEFAULT_TABLE_SIZE 101

#define MARLAIS_CONFIG_CHARACTER_CACHE 256
#define MARLAIS_CONFIG_RATIO_CACHE 16
#define MARLAIS_CONFIG_INTEGER_CACHE 1024
#define MARLAIS_CONFIG_UCHAR_CACHE 1024
#define MARLAIS_CONFIG_WCHAR_CACHE 1024

#endif
