/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
static yyconst short int yy_accept[142] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       36,    1,   35,    2,    2,    5,    2,    2,   31,   31,
       31,   31,    6,    7,    8,   31,   31,   31,   18,   31,
       19,   18,   19,   18,   11,   31,   18,   18,   19,   29,
       31,   18,    0,    5,    0,    0,    4,    0,    6,    0,
        0,   29,    0,   34,    0,    0,   22,   28,   23,   28,
       28,   28,    0,    0,    0,   11,    0,   14,   33,   32,
        0,   15,    0,   11,    0,    0,   21,   18,   18,   20,
       24,   29,   27,   30,    0,   30,    0,    3,    0,    0,
       29,   29,    0,   26,    0,   28,    9,   10,   12,   12,

       17,    0,   11,    0,   25,   14,    0,   32,   14,    0,
       13,   29,    0,   16,    6,    9,   10,   12,   12,   13,
        0,   16,    0,   14,   14,    0,    0,   15,   13,   29,
       29,   16,   13,   16,   14,    0,   14,   15,   29,   14,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    7,    8,    9,   10,
       11,   12,   13,   11,   14,   15,   16,   17,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   11,   21,
       22,   23,   24,    7,   25,   25,   25,   25,   26,   25,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       28,   29,   11,    8,    7,    1,   25,   30,   25,   25,

       26,   25,   27,   27,   27,   27,   27,   27,   27,   27,
       31,   27,   27,   27,   27,   27,   27,   27,   27,   32,
       27,   27,   11,    8,   11,   33,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[34] =
    {   0,
        1,    1,    2,    3,    1,    1,    3,    3,    4,    1,
        1,    3,    5,    6,    1,    3,    7,    7,    7,    8,
        3,    3,    3,    3,    9,    9,   10,    1,    1,    9,
       10,   10,    3
    } ;

static yyconst short int yy_base[164] =
    {   0,
      301,  293,  292,    0,  288,   31,  287,  280,   63,    0,
      282,  522,  522,  522,    2,  522,  273,  256,  522,    5,
      252,  261,  261,  522,  522,   72,    6,  100,  108,  228,
      522,    0,    5,    0,  137,   16,  229,    6,  226,  226,
      163,  203,    7,  522,  221,  200,  522,  216,  210,  209,
        0,  177,    8,  522,    0,   16,  522,    0,  522,  184,
       22,  196,  173,   38,   25,  214,  165,   33,  522,    0,
      226,   89,   36,    0,  228,  248,  522,  522,    0,    0,
      522,  158,  522,  522,  135,  101,  116,  522,  106,   46,
      248,    0,   95,  522,    0,    0,   84,   94,    0,  267,

      522,   99,    0,  100,  522,  103,  123,    0,  155,  129,
      129,  280,  170,  173,   58,   29,  148,    0,    0,  176,
      181,  199,  217,  220,  230,  192,  252,  270,  284,  293,
      301,  297,  317,  320,  323,  326,  329,  332,    0,  335,
      522,  354,  364,  374,  384,  389,  399,  407,  417,  427,
      435,  445,  455,  463,  473,  478,  488,  492,  497,  500,
      503,  508,  514
    } ;

static yyconst short int yy_def[164] =
    {   0,
      142,  142,  143,  143,  144,  144,  145,  145,  141,    9,
      141,  141,  141,  141,  141,  141,  141,  146,  141,  141,
      146,  147,  141,  141,  141,  148,  149,  141,  148,  150,
      141,  141,  141,  141,  141,  141,   29,   29,  141,  151,
      141,  141,  141,  141,  152,  146,  141,  147,  141,  153,
       29,  154,  149,  141,  149,  155,  141,  156,  141,  156,
      156,  141,  141,  150,  141,  141,  141,  141,  141,  157,
       35,  141,   71,   35,   71,   75,  141,  141,   29,   29,
      141,  151,  141,  141,  141,  141,  152,  141,  153,  153,
      154,   91,  155,  141,  155,  156,  141,  141,  158,  141,

      141,  141,   66,  159,  141,  141,  160,  157,  141,  161,
       71,  162,   71,   71,  141,  141,  141,  158,  100,  141,
      141,  141,  141,  141,  141,  163,  141,  141,   71,  162,
      130,   71,  141,  141,  141,  141,  141,  141,  131,  141,
        0,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141
    } ;

static yyconst short int yy_nxt[556] =
    {   0,
      141,   15,   16,   43,   44,   17,   43,   44,   43,   44,
       54,   69,   54,  141,   65,   70,   66,   66,   66,   67,
       94,   68,   68,   68,   18,   18,   18,   79,   80,   18,
       18,   18,   20,   16,   55,   77,   55,   78,   98,   98,
      141,   68,   68,   68,   95,  116,   63,   90,  115,  106,
      106,  106,  111,  111,  111,   21,   21,   21,  107,   50,
       21,   21,   21,   19,   24,   25,   26,   27,   28,   26,
       29,   30,   31,   31,   29,   32,   32,   33,   34,   35,
       35,   35,   36,   37,   38,   37,   39,   40,   40,   40,
       31,   41,   40,   40,   40,   42,   52,   52,   52,   94,

      116,   52,   52,   52,   56,  109,  109,  109,  115,   57,
      117,  117,  121,  121,  110,  120,  120,  120,   88,  106,
      106,  106,   84,   95,   58,   58,   58,   59,  107,   60,
       61,   62,   52,   52,   52,  123,  123,   52,   52,   52,
       71,  127,  127,   71,   71,  129,  129,  129,   71,   71,
       71,   72,   73,   74,   74,   74,   84,   71,   71,   71,
       71,   75,   76,   75,  117,  117,   75,   75,   75,   71,
       84,  125,  125,  125,   84,   84,   84,   83,   84,  105,
      126,  101,   85,   86,   86,   86,  114,  114,  114,  132,
      132,  132,  133,  133,  133,   86,   83,  122,  122,  122,

       97,   92,   92,   92,  136,  136,   92,   92,   92,   96,
       90,   50,   99,   99,   99,  134,  134,  134,   49,   47,
      100,  100,   96,   88,   78,  100,   96,   96,   72,  102,
      103,  103,  103,  124,  124,  124,  135,  135,  135,  104,
      141,   71,   71,   71,   71,   83,  125,  125,  125,   81,
       79,   75,  112,  112,  112,  126,   64,  112,  112,  112,
      113,  113,   50,   49,  114,  114,  114,   83,  128,  128,
      128,   47,   92,   92,   92,   47,   45,   92,   92,   92,
       96,  141,   23,  118,  118,  118,  138,  138,  138,   23,
       13,  119,  119,   96,   13,   13,  119,   96,   96,   83,

      129,  129,  129,   13,  131,  131,  131,  141,  141,  131,
      131,  131,   83,  132,  132,  132,  141,  139,  139,  139,
      141,  141,  139,  139,  139,  131,  131,  131,  141,  141,
      131,  131,  131,  133,  133,  133,  134,  134,  134,  135,
      135,  135,  137,  137,  137,  140,  140,  140,  138,  138,
      138,  140,  140,  140,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   46,   46,   46,   46,   46,   48,

       48,   48,   48,   48,   48,   48,   48,   48,   48,   51,
      141,   51,   51,   51,  141,   51,   51,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   63,   63,   63,
      141,   63,   63,   63,   63,   63,   63,   82,  141,   82,
       82,   82,   82,   82,   82,   87,   87,   87,   87,   87,
       87,   87,   87,   87,   87,   89,  141,   89,   89,   89,
       89,   89,   89,   89,   89,   91,  141,   91,   91,   91,
       91,   91,   91,   93,   93,   93,   93,   93,   93,   93,
       93,   93,   93,   96,  141,  141,   96,   96,  108,  141,
      108,  108,  108,  108,  108,  108,  108,  108,  118,  141,

      118,  122,  122,  122,  124,  124,  124,  128,  128,  128,
      130,  141,  130,  130,  130,  130,  130,  130,  137,  137,
      137,   11,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141
    } ;

static yyconst short int yy_chk[556] =
    {   0,
        0,    4,    4,   15,   15,    4,   20,   20,   43,   43,
       27,   34,   53,    0,   32,   34,   32,   32,   32,   33,
       56,   33,   33,   33,    4,    4,    4,   38,   38,    4,
        4,    4,    6,    6,   27,   36,   53,   36,   61,   61,
       64,   65,   65,   65,   56,  116,   64,   90,   90,   68,
       68,   68,   73,   73,   73,    6,    6,    6,   68,  115,
        6,    6,    6,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,   26,   26,   26,   93,

       97,   26,   26,   26,   28,   72,   72,   72,   89,   28,
       98,   98,  104,  104,   72,  102,  102,  102,   87,  106,
      106,  106,   86,   93,   28,   28,   28,   28,  106,   28,
       28,   28,   29,   29,   29,  107,  107,   29,   29,   29,
       35,  110,  110,   35,   35,  111,  111,  111,   35,   35,
       35,   35,   35,   35,   35,   35,   85,   35,   35,   35,
       35,   35,   35,   35,  117,  117,   35,   35,   35,   35,
       41,  109,  109,  109,   41,   41,   41,   82,   41,   67,
      109,   63,   41,   41,   41,   41,  113,  113,  113,  114,
      114,  114,  120,  120,  120,   41,   52,  121,  121,  121,

       60,   52,   52,   52,  126,  126,   52,   52,   52,   62,
       50,   49,   62,   62,   62,  122,  122,  122,   48,   46,
       62,   62,   62,   45,   42,   62,   62,   62,   66,   66,
       66,   66,   66,  123,  123,  123,  124,  124,  124,   66,
       71,   71,   71,   71,   71,   40,  125,  125,  125,   39,
       37,   71,   75,   75,   75,  125,   30,   75,   75,   75,
       76,   76,   23,   22,   76,   76,   76,   91,  127,  127,
      127,   21,   91,   91,   91,   18,   17,   91,   91,   91,
      100,   11,    8,  100,  100,  100,  128,  128,  128,    7,
        5,  100,  100,  100,    3,    2,  100,  100,  100,  112,

      129,  129,  129,    1,  112,  112,  112,    0,    0,  112,
      112,  112,  130,  132,  132,  132,    0,  130,  130,  130,
        0,    0,  130,  130,  130,  131,  131,  131,    0,    0,
      131,  131,  131,  133,  133,  133,  134,  134,  134,  135,
      135,  135,  136,  136,  136,  137,  137,  137,  138,  138,
      138,  140,  140,  140,  142,  142,  142,  142,  142,  142,
      142,  142,  142,  142,  143,  143,  143,  143,  143,  143,
      143,  143,  143,  143,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  146,  146,  146,  146,  146,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  147,  148,
        0,  148,  148,  148,    0,  148,  148,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  150,  150,  150,
        0,  150,  150,  150,  150,  150,  150,  151,    0,  151,
      151,  151,  151,  151,  151,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  153,    0,  153,  153,  153,
      153,  153,  153,  153,  153,  154,    0,  154,  154,  154,
      154,  154,  154,  155,  155,  155,  155,  155,  155,  155,
      155,  155,  155,  156,    0,    0,  156,  156,  157,    0,
      157,  157,  157,  157,  157,  157,  157,  157,  158,    0,

      158,  159,  159,  159,  160,  160,  160,  161,  161,  161,
      162,    0,  162,  162,  162,  162,  162,  162,  163,  163,
      163,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "dylan.l"
#define INITIAL 0
#line 2 "dylan.l"
/*
   Lexical analyzer for Dylan interm report tokens

   This software is free software; you can redistribute it and/or
   modify it under the terms of the GNU Library General Public
   License as published by the Free Software Foundation; either
   version 2 of the License, or (at your option) any later version.

   This software is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   Library General Public License for more details.

   You should have received a copy of the GNU Library General Public
   License along with this software; if not, write to the Free
   Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

   Original copyright notice follows:

   Copyright 1994, Joseph N. Wilson.  All Rights Reserved.
   Permission to use, copy, and modify this software and its
   documentation is hereby granted only under the following terms and
   conditions.  Both the above copyright notice and this permission
   notice must appear in all copies of the software, derivative works
   or modified version, and both notices must appear in supporting
   documentation.  Users of this software agree to the terms and
   conditions set forth in this notice.

 */

#ifdef sun
#include <floatingpoint.h>
#endif

#if defined(MACOS)
#include <unix.h>
#else
#include <sys/types.h>
#ifdef _WIN32
#include <time.h>
#else
#include <sys/time.h>
#endif
#endif

#include <string.h>

#include "alloc.h"
#include "bytestring.h"
#include "character.h"
#include "dylan.tab.h"
#include "globaldefs.h"
#include "list.h"
#include "number.h"
#include "object.h"
#include "symbol.h"
#include "yystype.h"

#ifdef BIG_INTEGERS
#include "biginteger.h"
#endif

extern char* prompt_continuation;
extern int yyerrflag;
extern int yydebug;
extern int load_file_context;

int yylineno = 1;

int charready (FILE *stream);
int strcasecmp (const char *s1, const char *s2);

Object header_key;
Object header_val;

/* reserved struct and tables */

struct resword
{
	char *word;
	int token;
	Object *symbol;
};

#define NUM_COREWORDS 8

struct resword coreword_table [NUM_COREWORDS] =
{	
	{"define", DEFINE, &define_symbol},
	{"end", END, &end_symbol},
	{"generic", GENERIC, &generic_symbol},
	{"handler", HANDLER, &handler_symbol},
	{"let", LET, &let_symbol},
	{"local", LOCAL, &local_symbol},
	{"method", METHOD, &method_symbol},
	{"otherwise", OTHERWISE, &otherwise_symbol},
};

#define NUM_BEGIN_WORDS	9

struct resword begin_word_table [NUM_BEGIN_WORDS] =
{
	{"begin", BEGIN_TOKEN, &begin_symbol},
	{"block", BLOCK, &block_symbol},
	{"case", CASE, &case_symbol},
	{"for", FOR, &for_symbol},
	{"if", IF, &if_symbol},
	{"select", SELECT, &select_symbol},
	{"unless", UNLESS, &unless_symbol},
	{"until", UNTIL, &until_symbol},
	{"while", WHILE, &while_symbol},
};

#define NUM_DEFINING_WORDS	6

struct resword defining_word_table [NUM_DEFINING_WORDS] =
{
	{"class", CLASS, &class_symbol},
	{"constant", CONSTANT, &constant_symbol},
	{"library", LIBRARY, &library_symbol},
	{"module", MODULE, &module_symbol},	
	{"test", TEST, &test_symbol},
	{"variable", VARIABLE, &variable_symbol},
};


/* intermediate word struct and tables */

struct intermediate_word_struct {
    int num_words;
    struct resword *reswords;
    struct intermediate_word_struct *next;
    
}
*intermediate_words;

#define NUM_IF_INTERMEDIATE_WORDS	2
struct resword if_intermediate_word_table [NUM_IF_INTERMEDIATE_WORDS] =
{
	{"else", ELSE, &else_symbol},
	{"elseif", ELSEIF, &elseif_symbol},
};

#define NUM_SELECT_INTERMEDIATE_WORDS	1
struct resword select_intermediate_word_table [NUM_SELECT_INTERMEDIATE_WORDS] =
{
	{"by", BY, &by_symbol},
};

#define NUM_CLASS_INTERMEDIATE_WORDS	1
struct resword class_intermediate_word_table [NUM_CLASS_INTERMEDIATE_WORDS] =
{
	{"slot", SLOT, &slot_symbol},
};

#define NUM_FOR_INTERMEDIATE_WORDS	1
struct resword for_intermediate_word_table [NUM_FOR_INTERMEDIATE_WORDS] =
{
	{"finally", FINALLY, &finally_symbol},
};

#define NUM_FOR_CLAUSE_WORDS		7
struct resword for_clause_word_table [NUM_FOR_CLAUSE_WORDS] =
{
    {"then", THEN, &then_symbol},
    {"in", IN, &in_symbol},
    {"from", FROM, &from_symbol},
    {"to", TO, &to_symbol},
    {"above", ABOVE, &above_symbol},
    {"below", BELOW, &below_symbol},
    {"by", BY, &by_symbol},
};

#define NUM_BLOCK_INTERMEDIATE_WORDS	3
struct resword block_intermediate_word_table [NUM_BLOCK_INTERMEDIATE_WORDS] =
{
	{"afterwards", AFTERWARDS, &afterwards_symbol},
	{"cleanup", CLEANUP, &cleanup_symbol},
	{"exception", EXCEPTION, &exception_symbol},
};

#define NUM_MODULE_INTERMEDIATE_WORDS	3
struct resword module_intermediate_word_table [NUM_MODULE_INTERMEDIATE_WORDS] =
{
	{"use", USE, &use_symbol},
	{"export", EXPORT, &export_symbol},
	{"create", CREATE, &create_symbol},
};

/*  */

extern Object yylval;
int search_for_poundword (char *string, YYSTYPE *obj_ptr);
int symbol_or_resword (char *string, YYSTYPE *obj_ptr);
static struct resword *search_for_resword (char *string,
					   struct resword *resword_table,
					   int num_ords);
int resword_compare (struct resword *c1, struct resword *c2);

static struct resword *search_intermediate_word (char *string);

static void process_unrecognized_character (char *yytext);
int which_operator (char *string, int length);
void push_intermediate_words (Object begin_word);
void pop_intermediate_words (void);

void make_header_key (void);
void make_header_end (void);
void make_header_val (void);

char *get_nonws_symbol (char *text);
char expand_escaped_character (char ch);
char* make_expanded_byte_string (char *str);

static int countlines(char *str);
#define INI 1
#define KEY 2
#define VAL 3
#define ETC 4

/* start contexts courtesy of Roger Critchlow */
#line 755 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 233 "dylan.l"


#line 908 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 142 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 522 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 235 "dylan.l"
{ BEGIN(INI);
		  yyless(0);
		}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INI):
case YY_STATE_EOF(KEY):
case YY_STATE_EOF(VAL):
case YY_STATE_EOF(ETC):
#line 239 "dylan.l"
{ yylval = eof_object;
					  return EOF_TOKEN;
					}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 243 "dylan.l"
{ BEGIN(ETC);
		  yyless(0);
		}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 247 "dylan.l"
{ BEGIN(KEY);
		  /* warn(line_count, "ignoring initial #! interpreter comment\n"); */
		  /* line_count++; */
		  ++yylineno;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 253 "dylan.l"
{ BEGIN(VAL);
				  make_header_key();
				  return yylex();
				}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 258 "dylan.l"
{ BEGIN(ETC);
			  ++yylineno;
			  make_header_end ();
			  return yylex ();
			}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 264 "dylan.l"
{ BEGIN(KEY);
				  yylineno += countlines (yytext);
				  make_header_val ();
				  return yylex ();
				}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 270 "dylan.l"
{ }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 272 "dylan.l"
{ /* Bogus hack! */
		  ++yylineno;
		  if (yyerrflag == 3) {
		      return ';';
		  } else if (! load_file_context) {
		      /* <pcb> not if loading from a file! */
		      if (! charready(yyin)) {
			  printf(prompt_continuation);
			  fflush (stdout); 
		      }
		  }
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 285 "dylan.l"
{ /* binary integer */ 
		  yylval = make_integer (strtol (yytext+2, NULL, 2));
		  return (LITERAL);
		}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 290 "dylan.l"
{ /* octal-integer */
		  yylval = make_integer (strtol (yytext+2, NULL, 8));
		  return (LITERAL);
		}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 295 "dylan.l"
{ /* decimal integer */
#ifdef BIG_INTEGERS
			if (strlen(yytext) >= 10)
				yylval = make_big_integer_str(yytext, 10);
			else
				yylval = make_integer (strtol (yytext, NULL, 10));
#else
    		  yylval = make_integer (strtol (yytext, NULL, 10));
#endif
		  return (LITERAL);
		}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 307 "dylan.l"
{ /* hex-integer */
			    yylval = make_integer (strtol (yytext+2, NULL, 16));
			    return (LITERAL);
			  }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 312 "dylan.l"
{ /* ratio */ 
				  char *ptr;
				  long numerator, denominator;
				  numerator = strtol (yytext, &ptr, 10);
				  denominator = strtol (ptr + 1, NULL, 10);
				  yylval = make_ratio (numerator, denominator);
				  return (LITERAL);
				}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 321 "dylan.l"
{ yylval = make_dfloat (strtod (yytext, NULL));
					  return (LITERAL);
					}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 324 "dylan.l"
{ yylval = make_dfloat (strtod (yytext, NULL));
				  return (LITERAL);
				}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 327 "dylan.l"
{ yylval = make_dfloat (strtod (yytext, NULL));
				  return (LITERAL);
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 331 "dylan.l"
{ char ch = yytext [yyleng-2];
			   yylval =
			    make_character(yytext[1] == '\\' ?
					   expand_escaped_character(ch) : ch );
			   return (LITERAL);
			 }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 339 "dylan.l"
{ /* OPERATOR  SYMBOL */ 
			  return which_operator(yytext, yyleng);
			}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 343 "dylan.l"
{ /* return char as token */
				  yylval = (Object)0;
				  return *yytext;
				}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 348 "dylan.l"
{ yylval = equal_arrow_symbol;
		  return (EQUAL_ARROW);
		}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 352 "dylan.l"
{ yylval = colon_colon_symbol;
		  return (COLON_COLON);
		 }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 356 "dylan.l"
{ yylval = NULL;
		  return (HASH_PAREN);
		 }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 360 "dylan.l"
{ yylval = NULL;
		  return (HASH_BRACKET);
		 }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 364 "dylan.l"
{ yylval = NULL;
		  return (QUESTION_QUESTION);
		 }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 368 "dylan.l"
{ yylval = NULL;
		  return (ELLIPSIS);
		 }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 372 "dylan.l"
{ /* Do some nasty business with yytext */
		  yytext[yyleng-1] = ':';
		  yylval = make_keyword (yytext + 2);
		  return (KEYWORD);
		}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 378 "dylan.l"
{
		  yylval = make_keyword (yytext);
		  if (yydebug) {
			printf("yydebug: got symbol [%s]\n",  yytext);
			}
		  return (KEYWORD);
		 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 386 "dylan.l"
{ return search_for_poundword (yytext, &yylval);
			}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 390 "dylan.l"
{ int tmp = symbol_or_resword (yytext, &yylval);
		  if (yydebug && tmp == SYMBOL) {
			printf ("yydebug: got symbol [%s]\n", yytext);
			}
		  return tmp;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 397 "dylan.l"
{ which_operator (yytext+1, yyleng-1);
		  return SYMBOL;
		}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 401 "dylan.l"
{ process_unrecognized_character (yytext);
			}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 404 "dylan.l"
{ }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 406 "dylan.l"
{ int ch;
		  loop:
			do {
				ch = input();
				if (ch == '\n')
					++yylineno;
				else
				if (ch == EOF)
					break;
			} while (ch != '*');
		  inner:
		      	switch (input()) {
			case EOF:
			case '/': break;
			case '*': goto inner;
			case '\n': ++yylineno;
			default: goto loop;
		      }
		}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 426 "dylan.l"
{ yytext[yyleng-1] = '\0';
		  yylval = make_expanded_byte_string (yytext+1);
		  return (STRING);
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 431 "dylan.l"
ECHO;
	YY_BREAK
#line 1301 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 142 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 142 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 141);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 431 "dylan.l"

int yywrap() { return 1; }

int
search_for_poundword (char *string, YYSTYPE *obj_ptr)
{
    switch (string[1]) {
    case 't':
    case 'T':
	if (yyleng == 2) {
	    *obj_ptr = true_object;
	    return HASH_T;
	}
	break;
    case 'f':
    case 'F':
	if (yyleng == 2) {
	    *obj_ptr = false_object;
	    return HASH_F;
	}
	break;
    case 'n':
    case 'N':
	if (strcasecmp (string, "#next") == 0) {
	    *obj_ptr = next_symbol;
	    return HASH_NEXT;
	}
	break;
    case 'r':
    case 'R':
	if (strcasecmp (string, "#rest") == 0) {
	    *obj_ptr = hash_rest_symbol;
	    return HASH_REST;
	}
	break;
	
    case 'k':
    case 'K':
	if (strcasecmp (string, "#key") == 0) {
	    *obj_ptr = key_symbol;
	    return HASH_KEY;
	}
	break;
    case 'a':
    case 'A':
	if (strcasecmp (string, "#all-keys") == 0) {
	    *obj_ptr = allkeys_symbol;
	    return HASH_ALL_KEYS;
	}
	break;
    }
    obj_ptr = NULL;
    return UNRECOGNIZED;
}

int
symbol_or_resword (char *string, YYSTYPE *obj_ptr)
{
    struct resword *result, target;

    target.word = string;

    result = search_for_resword (string, coreword_table, NUM_COREWORDS);
    if (result) {
	*obj_ptr = *(result->symbol);
	return result->token;
    }
    /* 	Check for simple begin word */
    result = search_for_resword (string, begin_word_table, NUM_BEGIN_WORDS);
    if (result) {
	*obj_ptr = *(result->symbol);
	return result->token;
    }
    result = search_intermediate_word (string);
    if (result) {
	*obj_ptr = *(result->symbol);
	return result->token;
    }
    result = search_for_resword (string, defining_word_table,
				 NUM_DEFINING_WORDS);
    if (result) {
	*obj_ptr = *(result->symbol);
	return result->token;
    }
    *obj_ptr = make_symbol(string);
    return SYMBOL;
}

static struct resword *
search_for_resword(char *string, struct resword *table, int num_words)
{
    struct resword target;

    target.word = string;
    return (struct resword *)bsearch ((const void *)(&target),
	    (const void *) table,
	    num_words, sizeof (struct resword),
            (int (*)(const void *, const void *))resword_compare);
}

static struct resword *
search_intermediate_word (char *string)
{
    int i;

    if (intermediate_words) {
	for (i = 0; i < intermediate_words->num_words; i++) {
	    if (0 == strcasecmp(string,
				(intermediate_words->reswords)[i].word)) {
		return &((intermediate_words->reswords)[i]);
	    }
	}
    }
    return NULL;
}

int
resword_compare (struct resword *r1, struct resword *r2)
{
	return strcasecmp (r1->word, r2->word);
}

static void
process_unrecognized_character (char *yytext)
{
	unsigned c = *yytext;
	fprintf(stderr, "Unrecognized character '%c' (0x%02x).\n", c, c);
}

void
init_reserved_word_symbols (void)
{
    int i;

    intermediate_words = NULL;

    for (i = 0; i < NUM_COREWORDS; i++) {
	*(coreword_table[i].symbol) = make_symbol(coreword_table[i].word);
    }
    for (i = 0; i < NUM_BEGIN_WORDS; i++) {
	*(begin_word_table[i].symbol) =
	    make_symbol (begin_word_table[i].word);
    }
    for (i = 0; i < NUM_DEFINING_WORDS; i++) {
	*(defining_word_table[i].symbol) =
	    make_symbol (defining_word_table[i].word);
    }
    for (i = 0; i < NUM_IF_INTERMEDIATE_WORDS; i++) {
	*(if_intermediate_word_table[i].symbol) =
	    make_symbol (if_intermediate_word_table[i].word);
    }
    for (i = 0; i < NUM_SELECT_INTERMEDIATE_WORDS; i++) {
	*(select_intermediate_word_table[i].symbol) =
	    make_symbol (select_intermediate_word_table[i].word);
    } 
    for (i = 0; i < NUM_CLASS_INTERMEDIATE_WORDS; i++) {
	*(class_intermediate_word_table[i].symbol) =
	    make_symbol (class_intermediate_word_table[i].word);
    } 
    for (i = 0; i < NUM_FOR_INTERMEDIATE_WORDS; i++) {
	*(for_intermediate_word_table[i].symbol) =
	    make_symbol (for_intermediate_word_table[i].word);
    } 
    for (i = 0; i < NUM_FOR_CLAUSE_WORDS; i++) {
	*(for_clause_word_table[i].symbol) =
	    make_symbol (for_clause_word_table[i].word);
    }
   for (i = 0; i < NUM_BLOCK_INTERMEDIATE_WORDS; i++) {
	*(block_intermediate_word_table[i].symbol) =
	    make_symbol (block_intermediate_word_table[i].word);
    }
   for (i = 0; i < NUM_MODULE_INTERMEDIATE_WORDS; i++) {
	*(module_intermediate_word_table[i].symbol) =
	    make_symbol (module_intermediate_word_table[i].word);
    }
    equal_arrow_symbol = make_symbol("=>");    
    colon_colon_symbol = make_symbol("::");
}

int
which_operator( char *string, int length)
{
    if (length == 1) {
	switch (*string) {
	case '+':
	    yylval = plus_symbol;
	    break;
	case '-':
	    yylval = minus_symbol;
	    break;
	case '*':
	    yylval = times_symbol;
	    break;
	case '/':
	    yylval = divides_symbol;
	    break;
	case '^':
	    yylval = exponent_symbol;
	    break;
	case '<':
	    yylval = lesser_symbol;
	    break;
	case '>':
	    yylval = greater_symbol;
	    break;
	case '=':
	    yylval = equal_symbol;
	    break;
	case '&':
	    yylval = and_symbol;
	    break;
	case '|':
	    yylval = or_symbol;
	    break;
	case '~':
	    yylval = not_symbol;
	    break;
	}
	return *string;
    } else {
	switch (*string) {
	case '<':
	    yylval = lesser_equal_symbol;
	    return LESSER_EQUAL;
	case '>':
	    yylval = greater_equal_symbol;
	    return GREATER_EQUAL;
	case '=':
	    yylval = equal_equal_symbol;
	    return EQUAL_EQUAL;
	case '~':
	    yylval = not_equal_symbol;
	    return NOT_EQUAL;
	case ':':
	    yylval = colon_equal_symbol;
	    return COLON_EQUAL;
	}
    }
    /*
     * If control gets here, we're really in trouble.
     */
    abort();
}

void
push_intermediate_words(Object begin_word)
{
    struct intermediate_word_struct *new_table;

    new_table = (struct intermediate_word_struct *)
	checking_malloc (sizeof (struct intermediate_word_struct));

    if (begin_word == if_symbol) {
	new_table->num_words = NUM_IF_INTERMEDIATE_WORDS;
	new_table->reswords = if_intermediate_word_table;
    } else if (begin_word == select_symbol) {
	new_table->num_words = NUM_SELECT_INTERMEDIATE_WORDS;
	new_table->reswords = select_intermediate_word_table;
    } else if(begin_word == class_symbol) {
	new_table->num_words = NUM_CLASS_INTERMEDIATE_WORDS;
	new_table->reswords = class_intermediate_word_table;
    } else if (begin_word == for_symbol) {
	new_table->num_words = NUM_FOR_INTERMEDIATE_WORDS;
	new_table->reswords = for_intermediate_word_table;
	new_table->next = intermediate_words;
	intermediate_words = new_table;
	new_table = (struct intermediate_word_struct *)
	    checking_malloc (sizeof (struct intermediate_word_struct));
	new_table->num_words = NUM_FOR_CLAUSE_WORDS;
	new_table->reswords = for_clause_word_table;
    } else if (begin_word == block_symbol) {
	new_table->num_words = NUM_BLOCK_INTERMEDIATE_WORDS;
	new_table->reswords = block_intermediate_word_table;
    } else if (begin_word == module_symbol) {
	new_table->num_words = NUM_MODULE_INTERMEDIATE_WORDS;
	new_table->reswords = module_intermediate_word_table;
    }
    new_table->next = intermediate_words;
    intermediate_words = new_table;
}

void
pop_intermediate_words()
{
    intermediate_words = intermediate_words->next;
}

void
make_header_key()
{
	header_key = make_keyword (yytext);
}

void
make_header_end()
{

}

char *
get_nonws_symbol (char *text)
{
	char *buffer, *buf_ptr, *start_ptr, *end_ptr;

	for (start_ptr = text;
	     *start_ptr == ' ' || *start_ptr == '\t' || *start_ptr == '\f'
		|| *start_ptr == '\v';
	     start_ptr++);
	for (end_ptr = start_ptr;
	     *end_ptr != ' ' && *end_ptr != '\t' && *end_ptr != '\f'
		&& *end_ptr != '\v' && *end_ptr != '\n';
             end_ptr++);
	buf_ptr = buffer =
		(char *) checking_malloc((end_ptr - start_ptr + 1) * sizeof (char));
	for(; start_ptr < end_ptr; *buf_ptr++ = *start_ptr++);
	*buf_ptr = '\0';
	return buffer;
}

void
make_header_val()
{
	if (header_key == module_keyword) {
		set_module (module_binding
			    (make_symbol (get_nonws_symbol (yytext))));
	}
}

int
charready (FILE *stream)
{
#ifdef MACOS
    return ((stdin)->cnt > 0);
#elif defined (_WIN32)
	return ((stdin)->_cnt > 0);
#else
    fd_set  readfds;
    int  nfound;
    struct timeval  timeout;

    if (yylval == eof_object) {
	/* This horrible kludge makes a prompt print after a file load */
        return 0;
    }
#ifdef __linux__
    if  (stream->_IO_read_end >= stream->_IO_read_ptr) {
#else
    if  (((stream)->_cnt) <= 0)  {
#endif
	FD_ZERO( &readfds );
	FD_SET( fileno( stream ), &readfds );
	timeout.tv_sec = 0;
	timeout.tv_usec = 300000;
	nfound = select( fileno( stream )+1, &readfds, 0, 0, &timeout );
	if  (nfound <= 0)  {
	    return 0;
	}
    }
    return 1;
#endif
}

void
yy_skip_ws()
{
    int c = '\0';

    /*
     * The check for yy_hold_char had to be added in upgrade to
     * flex 2.5.2 which `fixes' problems with beginning-of-line
     * conditions.  Without this check, marlais would print the
     * continuation prompt after each prompt due to not having
     * a charready but having input!
     */
    while ((yy_hold_char || charready (yyin)) &&	
	   ((c = input()) == ' ' || c == '\t' || c == '\f' 
		|| c == '\v' || c == '\n')){
    }
    if (c && c != '\n') {
	unput(c);
    }
}

void
yy_restart(FILE *new_file)
{
	yylineno = 1;
	yyrestart(new_file);
	BEGIN(INI);
}

char
expand_escaped_character (char ch)
{
	switch (ch) {
	case 'a':
		return '\a';
	case 'b':
		return '\b';
	case 'f':
		return '\f';
	case 'n':
		return '\n';
	case 'r':
		return '\r';
	case 't':
		return '\t';
	case 'v':
		return '\v';
	}
	return ch;
}

char* make_expanded_byte_string(char* str)
{
	char* backslash = strchr(str, '\\');
	if (backslash) {
		char* exp_str;
		Object obj;
		
		exp_str = checking_strdup (str);
		exp_str[0] = '\0';
		while (backslash) {
			backslash[0] = expand_escaped_character(backslash[1]);
			backslash[1] = '\0';
			strcat(exp_str, str);
			str = backslash + 2;
			backslash = strchr(str, '\\');
		}
		strcat(exp_str, str);

		obj = allocate_object (sizeof (struct byte_string));	
		BYTESTRTYPE (obj) = ByteString;
		BYTESTRSIZE(obj) = strlen (exp_str);
		BYTESTRVAL(obj) = exp_str;
		return (obj);
	}
	return make_byte_string(str);
}

static int countlines(char *str)
{
	int lines = 0;
	char c = *str++;
	while (c) {
		if (c == '\n') ++lines;
		c = *str++;
	}
	return lines;
}
